[common]
server_addr = frp.yulinsoft.top
server_port = 7000
log_file = /tmp/log/frpc.log
# trace, debug, info, warn, error
log_level = info
log_max_days = 2
pool_count = 5
token = 30174
tcp_mux = true
login_fail_exit = false

[k2_edu]
# tcp | udp | http | https, default is tcp
type = tcp
local_ip = 127.0.0.1
local_port = 22
use_compression = true
remote_port = 2204
[http_k2]
# tcp | udp | http | https, default is tcp
type = http
local_ip = 127.0.0.1
local_port = 80
use_compression = true
remote_port = 8080